### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by dirn-intg** [SethStormR/Droid-KDE#1]
- bssh
- bvnc
- avahi-discover
- conky
- calf
- deadbeef
- dosbox
- gzdoom
- qv4l2
- qvidcap
- qtractor
- stoken-gui
- stoken-gui-small
- timeshift
- ventoy
- yad-icon-browser
- yad-settings

**Comment by SethStormR** [comment]
Ah, I see you use Manjaro out of the missing icons, if I'm not mistaken ;)

I'll see to it, but there may go so some time, due to Christmas busyness for my part. Lets see if I can squeeze into this weekend.

**Comment by dirn-intg** [comment]
> Ah, I see you use Manjaro out of the missing icons, if I'm not mistaken ;)
> 
> I'll see to it, but there may go so some time, due to Christmas busyness for my part. Lets see if I can squeeze into this weekend.

I'm using Endeavour OS now :).
No worries bro, take your time and enjoy your holiday.
Wish you a happy Christmas holiday :)

**Comment by SethStormR** [comment]
Thanks.

Just installed Endeavour in VM to see which app and icons it uses.

**Comment by SethStormR** [comment]
All done and uploaded as v1.1

**Comment by dirn-intg** [comment]
Closing the issue. Thanks :)
